version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: 123
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ym_customer
    ports:
      - '5432:5432'
